#server:
#  port: 8091
#  error:
#    whitelabel:
#      enabled: false
#
#spring
#  datasource
#    url: jdbc:mysql://localhost:3306/Avocat_DB?createDatabaseIfNotExist=true
#    username: root
#    password: